name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      image:
        description: Choose what image to build.
        type: choice
        options:
          - build/dev-kit
          - build/runner
      build_only:
        description: Build the image but do not push to DockerHub.
        type: boolean
        default: false

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Parse Image Tag
      id: parse_tag
      run: |
        image_dir=$(echo "${{ github.event.inputs.image }}" | cut -d'/' -f1)
        image=$(echo "${{ github.event.inputs.image }}" | cut -d'/' -f2)
        echo "Image Directory: ${image_dir}"
        echo "Image Name: ${image}"
        echo "IMAGE_DIR=${image_dir}" >> $GITHUB_ENV
        echo "IMAGE=${image}" >> $GITHUB_ENV

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Authenticate to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}

    - name: Build and Push Image
      uses: docker/build-push-action@v6
      with:
        file: ${{ github.event.inputs.image }}.Dockerfile
        push: ${{ !github.event.inputs.build_only }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_DIR }}/${{ env.IMAGE }}:${{ github.sha }}
